### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by mpkelly** [auderer/stencil-styled-components#7]
Hi, 

Do you plan to support theming or is that something that should be handled by the app developer directly? I would like to do dynamic theming as is done with styled-components using a ThemeProvider. I can see that Stencil supports Contexts but as a Stencil newbie I am not sure how everything fits together. I am hoping to make the theme automatically available to every component that was created by the styled object - is this possible currently?

Thanks for your time. 

Mike

**Comment by michaelauderer** [comment]
Thanks for the interest in this library, Mike!

It would be great for us to support theming here. I currently don't have time to implement this, but I believe the best way would be using [StencilJS State Tunnels](https://stenciljs.com/docs/state-tunnel/).

In short, yes, it seems to be possible, but I don't have a timeframe for completion. Feel free to fork this repository and give it a try!

**Comment by MatheusBordin** [comment]
Hello guys! Good news, I did make simple implementation of ThemeProvider, working as expect in my tests. The pull-request can be look [here](https://github.com/auderer/stencil-styled-components/pull/9).

**Comment by auderer** [comment]
Closed in #9 by @MatheusBordin. Thanks a bunch for the contribution!
